// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

type PoolConfigMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseRateS     float64                `protobuf:"fixed64,1,opt,name=base_rate_s,json=baseRateS,proto3" json:"base_rate_s,omitempty"`
	BaseRateA     float64                `protobuf:"fixed64,2,opt,name=base_rate_a,json=baseRateA,proto3" json:"base_rate_a,omitempty"`
	BaseRateB     float64                `protobuf:"fixed64,3,opt,name=base_rate_b,json=baseRateB,proto3" json:"base_rate_b,omitempty"`
	SoftPityStart int32                  `protobuf:"varint,4,opt,name=soft_pity_start,json=softPityStart,proto3" json:"soft_pity_start,omitempty"`
	SoftPityInc   float64                `protobuf:"fixed64,5,opt,name=soft_pity_inc,json=softPityInc,proto3" json:"soft_pity_inc,omitempty"`
	HardPityS     int32                  `protobuf:"varint,6,opt,name=hard_pity_s,json=hardPityS,proto3" json:"hard_pity_s,omitempty"`
	HardPityA     int32                  `protobuf:"varint,7,opt,name=hard_pity_a,json=hardPityA,proto3" json:"hard_pity_a,omitempty"`
	MaxLimitedS   int32                  `protobuf:"varint,8,opt,name=max_limited_s,json=maxLimitedS,proto3" json:"max_limited_s,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolConfigMessage) Reset() {
	*x = PoolConfigMessage{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolConfigMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolConfigMessage) ProtoMessage() {}

func (x *PoolConfigMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolConfigMessage.ProtoReflect.Descriptor instead.
func (*PoolConfigMessage) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *PoolConfigMessage) GetBaseRateS() float64 {
	if x != nil {
		return x.BaseRateS
	}
	return 0
}

func (x *PoolConfigMessage) GetBaseRateA() float64 {
	if x != nil {
		return x.BaseRateA
	}
	return 0
}

func (x *PoolConfigMessage) GetBaseRateB() float64 {
	if x != nil {
		return x.BaseRateB
	}
	return 0
}

func (x *PoolConfigMessage) GetSoftPityStart() int32 {
	if x != nil {
		return x.SoftPityStart
	}
	return 0
}

func (x *PoolConfigMessage) GetSoftPityInc() float64 {
	if x != nil {
		return x.SoftPityInc
	}
	return 0
}

func (x *PoolConfigMessage) GetHardPityS() int32 {
	if x != nil {
		return x.HardPityS
	}
	return 0
}

func (x *PoolConfigMessage) GetHardPityA() int32 {
	if x != nil {
		return x.HardPityA
	}
	return 0
}

func (x *PoolConfigMessage) GetMaxLimitedS() int32 {
	if x != nil {
		return x.MaxLimitedS
	}
	return 0
}

func (x *PoolConfigMessage) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\x05proto\"\x0e\n" +
	"\fEmptyRequest\"\xc2\x02\n" +
	"\x11PoolConfigMessage\x12\x1e\n" +
	"\vbase_rate_s\x18\x01 \x01(\x01R\tbaseRateS\x12\x1e\n" +
	"\vbase_rate_a\x18\x02 \x01(\x01R\tbaseRateA\x12\x1e\n" +
	"\vbase_rate_b\x18\x03 \x01(\x01R\tbaseRateB\x12&\n" +
	"\x0fsoft_pity_start\x18\x04 \x01(\x05R\rsoftPityStart\x12\"\n" +
	"\rsoft_pity_inc\x18\x05 \x01(\x01R\vsoftPityInc\x12\x1e\n" +
	"\vhard_pity_s\x18\x06 \x01(\x05R\thardPityS\x12\x1e\n" +
	"\vhard_pity_a\x18\a \x01(\x05R\thardPityA\x12\"\n" +
	"\rmax_limited_s\x18\b \x01(\x05R\vmaxLimitedS\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt2Z\n" +
	"\rConfigService\x12I\n" +
	"\x16SubscribeConfigUpdates\x12\x13.proto.EmptyRequest\x1a\x18.proto.PoolConfigMessage0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_config_proto_goTypes = []any{
	(*EmptyRequest)(nil),      // 0: proto.EmptyRequest
	(*PoolConfigMessage)(nil), // 1: proto.PoolConfigMessage
}
var file_proto_config_proto_depIdxs = []int32{
	0, // 0: proto.ConfigService.SubscribeConfigUpdates:input_type -> proto.EmptyRequest
	1, // 1: proto.ConfigService.SubscribeConfigUpdates:output_type -> proto.PoolConfigMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
